version: '3.8'

services:
  zray:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/webui/zray.db:/app/webui/zray.db
    environment:
      - ZRAY_SECRET=zray-docker-secret-key
    restart: unless-stopped
